/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador;

import bases_de_datos.prof_mat_base_datos;
import clases.materia;
import clases.profesor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


public class asociar_profesor_materia extends javax.swing.JFrame {

    private final static String drv = "org.postgresql.Driver";//Dirver de conexion
    private final static String url = "jdbc:postgresql://localhost:5432/prueba_est"; // Ruta de conexion
    private final static String user = "postgres"; // nombre de la base de datos
    private final static String pass = "12345"; // Contraseña
    private static Connection Conexion;
    private static Statement SentenciaSQL;
    private DefaultComboBoxModel value;
    
    String cedula_profesor="",codigo_materia="";

    public asociar_profesor_materia() {
        initComponents();
        cargarComboProfesor();
    }

    public void cargarComboBD(String consulta) {

        try {
            Class.forName(drv);
            Conexion = DriverManager.getConnection(url, user, pass);
            SentenciaSQL = Conexion.createStatement();
            Statement SentenciaSQL = Conexion.createStatement();
            ResultSet materias = SentenciaSQL.executeQuery("SELECT materia.codigo_materia,materia.nombre_materia FROM materia WHERE materia.codigo_materia\n"
                    + "    NOT IN (SELECT prof_mat.codigo_materia FROM prof_mat where prof_mat.cedula_profesor='" + consulta + "') ");
            combo_materias.removeAllItems();

            value = new DefaultComboBoxModel();
            combo_materias.setModel(value);

            while (materias.next()) {
                // combo_materias.addItem(materias.getString(2));                
                //System.out.println(materias.getString(2));
                //combo_materias.addItem(new materia(materias.getString(1),materias.getString(2)));
                value.addElement(new materia(materias.getString(1), materias.getString(2)));
            }

            materias.close();
            Conexion.close();
            SentenciaSQL.close();

        } catch (ClassNotFoundException e) {
            System.out.println("Clase no encontrada  ");

        } catch (SQLException e) {
            System.out.println(e);

        }

    }

    
    public void cargarComboProfesor() {

        try {
            Class.forName(drv);
            Conexion = DriverManager.getConnection(url, user, pass);
            SentenciaSQL = Conexion.createStatement();
            Statement SentenciaSQL = Conexion.createStatement();
            ResultSet profesores = SentenciaSQL.executeQuery("select * from profesores");
            combo_profesores.removeAllItems();

            value = new DefaultComboBoxModel();            
            combo_profesores.setModel(value);

            while (profesores.next()) {
                // combo_materias.addItem(materias.getString(2));                
                //System.out.println(materias.getString(2));
                //combo_materias.addItem(new materia(materias.getString(1),materias.getString(2)));
                value.addElement(new profesor(profesores.getString(1), profesores.getString(2),profesores.getString(3)));
            }

          profesores.close();
            Conexion.close();
            SentenciaSQL.close();

        } catch (ClassNotFoundException e) {
            System.out.println("Clase no encontrada  ");

        } catch (SQLException e) {
            System.out.println(e);

        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo_materias = new javax.swing.JComboBox();
        boton_guardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        boton_consultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Materias = new javax.swing.JLabel();
        combo_profesores = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        combo_materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_materiasActionPerformed(evt);
            }
        });

        boton_guardar.setText("Guardar");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        boton_consultar.setText("OK");
        boton_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_consultarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo profesor");

        Materias.setText("Materias");

        combo_profesores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Profesor" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Agregar materia a profesor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(boton_guardar)
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(Materias))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo_materias, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combo_profesores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(boton_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_consultar)
                    .addComponent(jLabel1)
                    .addComponent(combo_profesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(combo_materias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Materias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_guardar)
                    .addComponent(jButton2))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_consultarActionPerformed
        profesor aux_prof = (profesor) combo_profesores.getSelectedItem();
        cedula_profesor=aux_prof.getCedula();
        cargarComboBD(aux_prof.getCedula());
    }//GEN-LAST:event_boton_consultarActionPerformed

    private void combo_materiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_materiasActionPerformed
       materia aux = (materia) combo_materias.getSelectedItem();
       codigo_materia=aux.getCodigo();
       // JOptionPane.showMessageDialog(rootPane, aux.getCodigo());
    }//GEN-LAST:event_combo_materiasActionPerformed

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
      prof_mat_base_datos pro = new prof_mat_base_datos();
      
        if (!cedula_profesor.equals("") && !codigo_materia.equals("")) {
            pro.ingresar(cedula_profesor,codigo_materia);
            
            if (pro.getResultado().equals("ok")) {
                JOptionPane.showMessageDialog(this, "Materia agregada correctamnete al profesor");
                 this.dispose();
            }
            
            else{
                JOptionPane.showMessageDialog(this, "El profesor ya tiene 3 materias asociadas");
            }
            
            
            
        }
      
      
    }//GEN-LAST:event_boton_guardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asociar_profesor_materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asociar_profesor_materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asociar_profesor_materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asociar_profesor_materia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new asociar_profesor_materia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Materias;
    private javax.swing.JButton boton_consultar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JComboBox combo_materias;
    private javax.swing.JComboBox combo_profesores;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
