package administrador;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class listar_estudiantes extends javax.swing.JFrame {

    /**
     * Creates new form listar_estudiantes
     */
    public listar_estudiantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_notas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        boton_listar_estudiantes = new javax.swing.JButton();
        boton_listar_profesores = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        boton_listar_materias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tabla_notas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_notas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Listar");

        boton_listar_estudiantes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_listar_estudiantes.setText("Listar Estudiantes");
        boton_listar_estudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_listar_estudiantesActionPerformed(evt);
            }
        });

        boton_listar_profesores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_listar_profesores.setText("Listar Profesores");
        boton_listar_profesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_listar_profesoresActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        boton_listar_materias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_listar_materias.setText("Listar Materias");
        boton_listar_materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_listar_materiasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(234, 234, 234))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(boton_listar_estudiantes)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton_listar_materias)
                        .addGap(18, 18, 18)
                        .addComponent(boton_listar_profesores)
                        .addGap(0, 42, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_listar_estudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_listar_profesores, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_listar_materias, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_listar_estudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_listar_estudiantesActionPerformed
        llenar_tabla("select codigo_estudiante as codigo,nombre_estudiante as nombre,telefono_estudiante as telefono from estudiantes");
        
    }//GEN-LAST:event_boton_listar_estudiantesActionPerformed

    private void boton_listar_profesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_listar_profesoresActionPerformed
        llenar_tabla("select * from profesores");
        
    }//GEN-LAST:event_boton_listar_profesoresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boton_listar_materiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_listar_materiasActionPerformed
        llenar_tabla("select codigo_materia as codigo,nombre_materia materia from materia");
    }//GEN-LAST:event_boton_listar_materiasActionPerformed

    
    public void llenar_tabla(String consulta){
        try {
            //Para establecer el modelo al JTable
            DefaultTableModel modelo = new DefaultTableModel();
            this.tabla_notas.setModel(modelo);
            //Para conectarnos a nuestra base de datos
            DriverManager.registerDriver(new org.postgresql.Driver());
            Connection conexion = DriverManager.getConnection("jdbc:postgresql://localhost:5432/prueba_est", "postgres", "12345");
            //Para ejecutar la consulta
            Statement s = conexion.createStatement();
            //Ejecutamos la consulta que escribimos en la caja de texto
            //y los datos lo almacenamos en un ResultSet
            ResultSet rs = s.executeQuery(consulta);
            //Obteniendo la informacion de las columnas que estan siendo consultadas
            ResultSetMetaData rsMd = rs.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas = rsMd.getColumnCount();
            //Establecer como cabezeras el nombre de las colimnas
            for (int i = 1; i <= cantidadColumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));

            }
            //Creando las filas para el JTable
            while (rs.next()) {
                Object[] fila = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
            rs.close();
            conexion.close();

//            tabla_notas.getColumnModel().getColumn(0).setMaxWidth(0);
//            tabla_notas.getColumnModel().getColumn(0).setMinWidth(0);
//            tabla_notas.getColumnModel().getColumn(0).setPreferredWidth(0);
            
            setAnchoColumnas();

//            jtQuery.getColumnModel().getColumn(1).setMaxWidth(0);
//            jtQuery.getColumnModel().getColumn(1).setMinWidth(0);
//            jtQuery.getColumnModel().getColumn(1).setPreferredWidth(0);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    
    
    
    
    
    public void setAnchoColumnas(){        
       // JViewport scroll =  (JViewport) tabla_notas.getParent(); 
        int ancho = jScrollPane1.getWidth(); 
        int anchoColumna = 0; 
        TableColumnModel modeloColumna = tabla_notas.getColumnModel(); 
        TableColumn columnaTabla; 
        for (int i = 0; i < tabla_notas.getColumnCount(); i++) { 
            columnaTabla = modeloColumna.getColumn(i); 
            switch(i){ 
                
                case 1: anchoColumna = (40*ancho)/100; 
                columnaTabla.setPreferredWidth(anchoColumna); 
                        break; 
////                case 2: anchoColumna = (50*ancho)/100; 
////                        break; 
//                case 3: anchoColumna = (20*ancho)/100; 
//                        break; 
            }                      
                       
        } 
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listar_estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listar_estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listar_estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listar_estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listar_estudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_listar_estudiantes;
    private javax.swing.JButton boton_listar_materias;
    private javax.swing.JButton boton_listar_profesores;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_notas;
    // End of variables declaration//GEN-END:variables
}
